language: python
python: 2.7
install:
  - python setup.py install
script:
  - echo "Placeholder for tests"
deploy:
  # Test PyPI
  - provider: pypi
    distributions: sdist bdist_wheel
    user: ExalDraen
    password:
      secure: "l7IJLxpDllZJ4vHS/FSE51GnN0FA/mjh/oE6cLUlUgfyHO99uZ1WWO39MwbSqmgUA2TF3vxNnIZHElOCoY2Y/JcNw9wlK1YdyPOxWk/lIE4pq4snMnzHPJbvwqIUj8kW4Vt611P2ezavYrb2ZgM6R8hohzObGa10htcXScPn3H6xorl+mDDPDU0DyAlPnGvsvO2X/fE6RiewsFKqfCGlJxRleU7EszMZBx7m8RX0mCNW+0qCajLPH8eT+vniv3JvjtrDOCMEF20ZbxPsqJFBwJVgbT7gN4ADqLpK1WYp1Pfg7R14Q4hrVP180JGBKcMhm6SwWvI2VqG1yrWV1dPI3vfRa6uMvtFt9R57ZKY2NDglUdrS84Wjwf0fvAxVtZ6iqNG0d6YIxyDVHCLM7wdYhZCFusczmvYGmgfOcDbuIXw85yPolFFZTiQkl3leTvtGm4eErI57ee0L8fMDKrkUNemKOi0M+xsOV22NoOkdNhJz6/RNPcn63XDKqKVctQToxgNHBZnSvnUa1n5uC/y4afgY4ienLvfnLvuBNVQhlt5o0lJpLLXKZVmeEqwGFjZ7Vef6elyB7aOM/lkc04+HtGooAC7Hjnlfrm6f435awHn8uJtD6i/qXS4Lv9d9g/+H02FdjtR5gKkmLBHRs6n2iUNWmLGIkX4YqW96UMV26pc="
    server: https://test.pypi.org/legacy/
    on:
      tags: true
      repo: ExalDraen/python-libsolace
      condition: "$TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
  # Live PyPI
  - provider: pypi
    distributions: sdist bdist_wheel
    user: ExalDraen
    password:
      secure: "xaljxxLdGl2JH/fwOSRrC5U6cWcSIMJBWBHg/fly5VgakMWskg26eIsB8pxaupjuO9PYj6XmOjuO95iemtXSuHPYZq76s84wqbKOxN0kKNqbteiWDqC7h9DDmNVp+3Is+GtisQIdYK0EeEX3gNjSqHCKz3etQKss0UBpJ9JRkeqUkZfQgkUoRJhBvBXCtYHXP+ExdMJHpAAbXuxnzU7VNS5NUInI29kP9ZhjsJ7D/5RRtxpwsz/NRdZXQLDAMOhOEJ1QiQ3qBXYd1lLYjr8tQQ9UK+Xa59Vgyr7Hd/DMLGiHVqpM9rN1VQaxQWpSY/aC4Pp/L5KnWHUnIVOrNgWemPv7KNgq/qIFmrDq0+8OU6afOmUZ8rlbDocFtbK8NUAmLKb5EXbKweKNkN/VwRTnDKXBZjStWxKJFFI7qotETiokgf8DIz/j1C9OA8N6rf7MPuAM7CPm3UPKLrLqt1ptWmgSkZtlzsZHZVYVc1B1PnJd3++eTCvSGm+b1tcY4vyGZAektwcRcQ8htBFGJ8FXJf5o3wAIfMWeyQbU4/34oxnu6nIWM3GkEWMezho3OHiCZivRUgSLX2VJZaoTxyrekv7BoEmqPlkQqXh191iTrWvRVAELx6/LKJK1ehZLqDz22q5MxLwCgF4s3P4P63T2yRBTU9CiJALOC1ArYK6Iteo="
    on:
      tags: true
      repo: ExalDraen/python-libsolace
      condition: "$TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+)?$"
