import os
import subprocess
from setuptools import setup

ROOT_DIR = os.path.dirname(__file__)
SOURCE_DIR = os.path.join(ROOT_DIR)

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

install_requires = [
    'ordereddict==1.1',
    'prettyprint==0.1.5',
    'simplejson==3.5.3',
    'pyparsing',
    'urllib3==1.9',
    'lxml==3.3.5',
    'pyyaml==3.11',
    'demjson==2.2.4'
]

try:
    import importlib
except ImportError:
    install_requires.append('importlib')

try:
    p = subprocess.Popen(['git', 'describe'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    o = p.communicate()
    if p.returncode != 0:
        raise Exception('git describe failed to execute reason: %s' % o[1])
    version_git = o[0].rstrip()
except:
    version_git = open(version_py).read().strip().split('=')[-1].replace('"', '')

version_msg = "# Do not edit this file, libsolace versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep + "__version__=" + version_git)

setup(name='libsolace',
      version="{ver}".format(ver=version_git),
      description='Solace Provisioning Helper',
      author='Kegan Holtzhausen',
      author_email='Kegan.Holtzhausen@unibet.com',
      packages=[
          'libsolace',
          'libsolace.data',
          'libsolace.plugins',
          'libsolace.items'
      ],
      package_data={'': ['*.xsd']},
      setup_requires=[
          'nose==1.3.3',
          'wheel', 'simplejson'
      ],
      tests_require=[
          'unittest2==0.5.1',
          'coverage==3.7.1'
      ],
      install_requires=install_requires,
      scripts=[
          'bin/solace-provision.py'
      ]
      )
